// Scans client/public/music/ for audio files and (re)writes
// src/data/tracks.generated.ts with one entry per file. Runs automatically
// before `npm run dev` and `npm run build` (see predev/prebuild), so you
// never edit a track list by hand — just drop files in and they appear.
//
// Filename → metadata convention (all optional):
//   "Artist - Title.mp3"        → artist "Artist",  title "Title"
//   "01 - Artist - Title.mp3"   → same, leading track number sets the order
//   "Title.mp3"                 → artist "Unknown Artist", title "Title"
// A cover image with the same base name (.jpg/.jpeg/.png/.webp/.gif) next to
// the audio file is picked up automatically as the track art.

import { readdirSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname, parse } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const MUSIC_DIR = join(here, "..", "public", "music");
const OUT_FILE = join(here, "..", "src", "data", "tracks.generated.ts");

const AUDIO_EXT = new Set([".mp3", ".m4a", ".aac", ".ogg", ".oga", ".wav", ".flac", ".webm"]);
const IMAGE_EXT = [".jpg", ".jpeg", ".png", ".webp", ".gif"];

if (!existsSync(MUSIC_DIR)) mkdirSync(MUSIC_DIR, { recursive: true });

const entries = readdirSync(MUSIC_DIR);
const images = new Set(entries.map((f) => f.toLowerCase()));

function findArt(base) {
  for (const ext of IMAGE_EXT) {
    const candidate = `${base}${ext}`;
    const match = entries.find((f) => f.toLowerCase() === candidate.toLowerCase());
    if (match) return `/music/${encodeURIComponent(match)}`;
  }
  return undefined;
}

function parseName(filename) {
  let name = parse(filename).name; // strip extension
  let order = null;

  // Optional leading track number: "01 - ", "01. ", "01 "
  const numMatch = name.match(/^\s*(\d+)\s*[-.]?\s+(.*)$/);
  if (numMatch && numMatch[2]) {
    order = parseInt(numMatch[1], 10);
    name = numMatch[2];
  }

  // "Artist - Title" (split on the first " - ")
  const dash = name.indexOf(" - ");
  let artist = "Unknown Artist";
  let title = name.trim();
  if (dash !== -1) {
    artist = name.slice(0, dash).trim();
    title = name.slice(dash + 3).trim();
  }
  return { artist, title, order };
}

function slug(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "track";
}

const audioFiles = entries
  .filter((f) => AUDIO_EXT.has(parse(f).ext.toLowerCase()))
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: "base" }));

const seen = new Set();
const tracks = audioFiles.map((file, i) => {
  const { artist, title, order } = parseName(file);
  let id = slug(`${artist}-${title}`);
  if (seen.has(id)) id = `${id}-${i}`;
  seen.add(id);
  const art = findArt(parse(file).name);
  return { id, title, artist, src: `/music/${encodeURIComponent(file)}`, art, order };
});

// Order by leading track number when present, otherwise keep the sorted order.
tracks.sort((a, b) => {
  if (a.order != null && b.order != null) return a.order - b.order;
  if (a.order != null) return -1;
  if (b.order != null) return 1;
  return 0;
});

const body = tracks
  .map((t) => {
    const fields = [
      `id: ${JSON.stringify(t.id)}`,
      `title: ${JSON.stringify(t.title)}`,
      `artist: ${JSON.stringify(t.artist)}`,
      `src: ${JSON.stringify(t.src)}`,
    ];
    if (t.art) fields.push(`art: ${JSON.stringify(t.art)}`);
    return `  { ${fields.join(", ")} },`;
  })
  .join("\n");

const out = `// AUTO-GENERATED by scripts/gen-tracks.mjs — do not edit by hand.
// Add/remove songs by dropping files in client/public/music/, then this file
// is rewritten on the next \`npm run dev\` / \`npm run build\` (or \`npm run tracks\`).
import type { Track } from "./tracks";

export const GENERATED_TRACKS: Track[] = [
${body}
];
`;

writeFileSync(OUT_FILE, out, "utf8");
console.log(`[gen-tracks] wrote ${tracks.length} track(s) to tracks.generated.ts`);
