// Scans client/public/gallery/ for images and (re)writes
// src/data/gallery.generated.ts with one entry per file. Runs automatically
// before `npm run dev` / `npm run build` (see predev/prebuild), so you never
// edit the gallery list by hand - drop images in and they appear.
//
// Two ways to set the category (pick whichever you like, you can mix them):
//
//   1) Subfolders = categories (easiest to organise):
//        public/gallery/Photography/sunset over water.jpg
//        public/gallery/Posters/jazz night.png
//      → categories "Photography" and "Posters".
//
//   2) Filename prefix for files at the top level:
//        public/gallery/Posters - Jazz Night.jpg   → category "Posters"
//        public/gallery/sunset.jpg                 → category "Gallery" (default)
//
// Title comes from the filename (extension stripped, underscores → spaces):
//   "01 - Jazz Night (2024).jpg" → title "Jazz Night", date "2024", sorts by 01
// The leading number sets order; a trailing (YYYY) or (YYYY-MM) sets the date.

import { readdirSync, writeFileSync, existsSync, mkdirSync, statSync } from "node:fs";
import { join, dirname, parse, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const GALLERY_DIR = join(here, "..", "public", "gallery");
const OUT_FILE = join(here, "..", "src", "data", "gallery.generated.ts");

const IMAGE_EXT = new Set([".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif", ".bmp", ".svg"]);
const DEFAULT_CATEGORY = "Gallery";

if (!existsSync(GALLERY_DIR)) mkdirSync(GALLERY_DIR, { recursive: true });

// Recursively collect image files as path segments relative to the root.
function walk(dir, base = []) {
  const out = [];
  for (const name of readdirSync(dir)) {
    if (name.startsWith(".")) continue;
    const abs = join(dir, name);
    if (statSync(abs).isDirectory()) {
      out.push(...walk(abs, [...base, name]));
    } else if (IMAGE_EXT.has(parse(name).ext.toLowerCase())) {
      out.push([...base, name]);
    }
  }
  return out;
}

function refineTitle(raw) {
  let t = raw;
  let order = null;
  let date;
  const num = t.match(/^\s*(\d+)\s*[-.]?\s+(.*)$/);
  if (num && num[2]) {
    order = parseInt(num[1], 10);
    t = num[2];
  }
  const dm = t.match(/\((\d{4}(?:-\d{2})?)\)\s*$/);
  if (dm) {
    date = dm[1];
    t = t.slice(0, dm.index).trim();
  }
  t = t.replace(/_/g, " ").trim();
  return { title: t || raw, order, date };
}

function slug(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "item";
}

const files = walk(GALLERY_DIR);
const seen = new Set();

const photos = files.map((parts) => {
  const fileName = parts[parts.length - 1];
  const nameNoExt = parse(fileName).name;

  let category;
  let titleRaw;
  if (parts.length > 1) {
    // Inside a subfolder → that folder is the category.
    category = parts[0];
    titleRaw = nameNoExt;
  } else {
    // Top-level file → optional "Category - Title".
    const dash = nameNoExt.indexOf(" - ");
    if (dash !== -1) {
      category = nameNoExt.slice(0, dash).trim();
      titleRaw = nameNoExt.slice(dash + 3).trim();
    } else {
      category = DEFAULT_CATEGORY;
      titleRaw = nameNoExt;
    }
  }

  const { title, order, date } = refineTitle(titleRaw);
  let id = slug(`${category}-${title}`);
  if (seen.has(id)) id = `${id}-${seen.size}`;
  seen.add(id);

  const src = "/gallery/" + parts.map(encodeURIComponent).join("/");
  return { id, title, category, src, date, order, _file: parts.join(sep) };
});

// Group by category (first seen wins ordering), then by leading number, then name.
const catOrder = [];
for (const p of photos) if (!catOrder.includes(p.category)) catOrder.push(p.category);
photos.sort((a, b) => {
  const c = catOrder.indexOf(a.category) - catOrder.indexOf(b.category);
  if (c !== 0) return c;
  if (a.order != null && b.order != null && a.order !== b.order) return a.order - b.order;
  if (a.order != null && b.order == null) return -1;
  if (a.order == null && b.order != null) return 1;
  return a._file.localeCompare(b._file, undefined, { numeric: true, sensitivity: "base" });
});

const body = photos
  .map((p) => {
    const fields = [
      `id: ${JSON.stringify(p.id)}`,
      `title: ${JSON.stringify(p.title)}`,
      `category: ${JSON.stringify(p.category)}`,
      `src: ${JSON.stringify(p.src)}`,
    ];
    if (p.date) fields.push(`date: ${JSON.stringify(p.date)}`);
    return `  { ${fields.join(", ")} },`;
  })
  .join("\n");

const out = `// AUTO-GENERATED by scripts/gen-gallery.mjs - do not edit by hand.
// Add/remove images by dropping files in client/public/gallery/, then this file
// is rewritten on the next \`npm run dev\` / \`npm run build\` (or \`npm run gallery\`).
import type { Photo } from "./gallery";

export const GENERATED_PHOTOS: Photo[] = [
${body}
];
`;

writeFileSync(OUT_FILE, out, "utf8");
console.log(`[gen-gallery] wrote ${photos.length} image(s) to gallery.generated.ts`);
