// Scans client/public/games/<slug>/ for self-hosted HTML5 game builds and
// (re)writes src/data/games.generated.ts. Drop a Godot/Unity HTML5 export into
//   client/public/games/<slug>/        (so .../index.html exists)
// where <slug> matches the game's content/projects/<slug>.md, and the game
// becomes playable inside a window (instead of opening on itch in a new tab).
// An optional cover image (cover.png / thumbnail.jpg / …) in the same folder
// becomes the card art.
//
// Runs automatically before `npm run dev` / `npm run build` (see the `gen`
// script), or run `npm run games` to refresh without restarting.

import { readdirSync, writeFileSync, existsSync, mkdirSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const GAMES_DIR = join(here, "..", "public", "games");
const OUT_FILE = join(here, "..", "src", "data", "games.generated.ts");

const COVER_NAMES = ["cover", "thumbnail", "thumb", "screenshot"];
const IMAGE_EXT = [".png", ".jpg", ".jpeg", ".webp", ".gif", ".avif"];

if (!existsSync(GAMES_DIR)) mkdirSync(GAMES_DIR, { recursive: true });

// First cover.*/thumbnail.* image in a build folder, if any.
function findCover(dirAbs) {
  const files = readdirSync(dirAbs).filter((f) => !f.startsWith("."));
  for (const base of COVER_NAMES) {
    for (const ext of IMAGE_EXT) {
      const hit = files.find((f) => f.toLowerCase() === base + ext);
      if (hit) return hit;
    }
  }
  return null;
}

const enc = (name) => `/games/${name.split("/").map(encodeURIComponent).join("/")}`;

const builds = [];
for (const name of readdirSync(GAMES_DIR)) {
  if (name.startsWith(".")) continue;
  const abs = join(GAMES_DIR, name);
  if (!statSync(abs).isDirectory()) continue;
  if (!existsSync(join(abs, "index.html"))) {
    console.warn(`[gen-games] skipping ${name}/ (no index.html)`);
    continue;
  }
  const coverFile = findCover(abs);
  builds.push({
    slug: name, // folder name = project slug (content/projects/<slug>.md)
    src: `${enc(name)}/index.html`,
    cover: coverFile ? `${enc(name)}/${encodeURIComponent(coverFile)}` : undefined,
  });
}

builds.sort((a, b) => a.slug.localeCompare(b.slug));

const entries = builds
  .map((b) => {
    const fields = [`src: ${JSON.stringify(b.src)}`];
    if (b.cover) fields.push(`cover: ${JSON.stringify(b.cover)}`);
    return `  ${JSON.stringify(b.slug)}: { ${fields.join(", ")} },`;
  })
  .join("\n");

const out = `// AUTO-GENERATED by scripts/gen-games.mjs — do not edit by hand.
// Drop an HTML5 export into client/public/games/<slug>/ (slug = the game's
// content/projects/<slug>.md name); this file is rewritten on the next
// \`npm run dev\` / \`npm run build\` (or \`npm run games\`).

export type GameBuild = { src: string; cover?: string };

// Keyed by project slug (the content/projects/*.md filename / Project id).
export const LOCAL_GAMES: Record<string, GameBuild> = {
${entries}
};
`;

writeFileSync(OUT_FILE, out, "utf8");
console.log(`[gen-games] wrote ${builds.length} local game build(s) to games.generated.ts`);
