// AUTO-GENERATED by scripts/gen-gallery.mjs — do not edit by hand.
// Add/remove images by dropping files in client/public/gallery/, then this file
// is rewritten on the next `npm run dev` / `npm run build` (or `npm run gallery`).
import type { Photo } from "./gallery";

export const GENERATED_PHOTOS: Photo[] = [
  { id: "gallery-djo", title: "djo", category: "Gallery", src: "/gallery/djo.png" },
  { id: "gallery-next-semester", title: "next semester", category: "Gallery", src: "/gallery/next%20semester.png" },
  { id: "gallery-trench", title: "trench", category: "Gallery", src: "/gallery/trench.png" },
];
