// AUTO-GENERATED by scripts/gen-gallery.mjs - do not edit by hand.
// Add/remove images by dropping files in client/public/gallery/, then this file
// is rewritten on the next `npm run dev` / `npm run build` (or `npm run gallery`).
import type { Photo } from "./gallery";

export const GENERATED_PHOTOS: Photo[] = [
  { id: "gallery-clancy", title: "clancy", category: "Gallery", src: "/gallery/clancy.png" },
  { id: "gallery-digitaldecay", title: "digitaldecay", category: "Gallery", src: "/gallery/digitaldecay.gif" },
  { id: "gallery-djo", title: "djo", category: "Gallery", src: "/gallery/djo.png" },
  { id: "gallery-something-is-missing", title: "something is missing", category: "Gallery", src: "/gallery/something%20is%20missing.jpg" },
  { id: "gallery-trench", title: "trench", category: "Gallery", src: "/gallery/trench.jpg" },
];
