// AUTO-GENERATED by scripts/gen-games.mjs - do not edit by hand.
// Drop an HTML5 export into client/public/games/<slug>/ (slug = the game's
// content/projects/<slug>.md name); this file is rewritten on the next
// `npm run dev` / `npm run build` (or `npm run games`). An entry with a
// cover but no src is art only - that game still opens on itch.

export type GameBuild = { src?: string; cover?: string };

// Keyed by project slug (the content/projects/*.md filename / Project id).
export const LOCAL_GAMES: Record<string, GameBuild> = {
  "astracipher": { src: "/games/astracipher/index.html", cover: "/games/astracipher/cover.png" },
  "puppetry": { cover: "/games/puppetry/cover.png" },
  "suhoor-rush": { src: "/games/suhoor-rush/index.html", cover: "/games/suhoor-rush/cover.png" },
};
