// AUTO-GENERATED by scripts/gen-library.mjs — do not edit by hand.
// Drop documents into client/public/library/<Shelf>/ (or run `npm run add:doc`);
// this file is rewritten on the next `npm run dev` / `npm run build` (or
// `npm run library`).
import type { LibraryDoc } from "./library";

export const GENERATED_LIBRARY: LibraryDoc[] = [
  { id: "poems/shapeshifter", shelf: "Poems", title: "shapeshifter", date: "2026-07", blurb: "I’m no stranger to the engine roar", format: "md", src: "/library/Poems/shapeshifter.md", fileName: "shapeshifter.md", bytes: 818, body: "I’m no stranger to the engine roar\n\nThat scores my bolting thoughts\n\nMy hands wringing in my lap\n\nToo damp to grip my seat\n\nI can only stare ahead\n\nThe scenery, distant and blear\n\nIt pulls me into a trance\n\nAnd when it floods my peripheral,\n\nI’ve crossed the line of no return.\n\nI befriend the flora and fauna\n\nThe solar might, the crops’ order\n\nHow people eat and work and play\n\nI project my life into their’s\n\nA shapeshifter stumbling upon kin\n\nI am one with this territory\n\nI am a citizen of this town\n\nThe steering wheel jolts away\n\nForsaking my precious town!\n\nThe scenery morphs into another\n\nMy vision blurs, my sight shifting\n\nInto another distant and blear view\n\n\nI find myself alien again\n\nThe whirling engine deafening my thoughts,\n\nI can only stare ahead.\n" },
];
