// AUTO-GENERATED by scripts/gen-projects.mjs — do not edit by hand.
// Add projects with `npm run add` (or edit content/projects/*.md); this file is
// rewritten on the next `npm run dev` / `npm run build` (or `npm run projects`).
import type { Project } from "./projects";

export const GENERATED_PROJECTS: Project[] = [
  { id: "portfolio-this-site", name: "Portfolio (this site)", category: "websites", blurb: "The Amiga-Workbench desktop you're looking at right now.", url: "https://nourin.is-a.dev", date: "2026-05" },
  { id: "tether-note", name: "Tether Note", category: "websites", blurb: "Time-delayed note delivery — send messages to your future self at custom intervals.", url: "https://tethernote.vercel.app/", date: "2025-11" },
  { id: "ssh-portfolio", name: "SSH Portfolio", category: "websites", blurb: "Fully interactive TUI portfolio served over SSH (Go + the Charmbracelet stack).", url: "https://nourin.is-a.dev", date: "2025-10" },
  { id: "subscriptions-tracker-api", name: "Subscriptions Tracker API", category: "apis", blurb: "RESTful subscription-management API — JWT auth and 15+ endpoints.", url: "https://github.com/nourinawadd/subscriptions-tracker-api", date: "2025-05" },
  { id: "task-manager-api", name: "Task Manager API", category: "apis", blurb: "Task Manager API with JWT auth, role-based access, and a relational PostgreSQL schema.", url: "https://github.com/nourinawadd/task-manager-api", date: "2025-04" },
  { id: "suhoor-rush", name: "Suhoor Rush", category: "games", blurb: "2D web game blending rapid item collection with narrative — built in 3 days for a jam.", url: "https://sifrstudios.itch.io/suhoor-rush", date: "2025-03" },
  { id: "puppetry", name: "Puppetry", category: "games", blurb: "2D puzzle for a power-themed jam — multi-puppet coordination, built in 9 days.", url: "https://sifrstudios.itch.io/puppetry", date: "2025-01" },
  { id: "astracipher", name: "AstraCipher", category: "games", blurb: "2D story-driven top-down platformer for dark-web awareness.", url: "https://sifrstudios.itch.io/astracipher", date: "2024-11" },
];
