// AUTO-GENERATED by scripts/gen-tracks.mjs — do not edit by hand.
// Add/remove songs by dropping files in client/public/music/, then this file
// is rewritten on the next `npm run dev` / `npm run build` (or `npm run tracks`).
import type { Track } from "./tracks";

export const GENERATED_TRACKS: Track[] = [
  { id: "unknown-artist-midwest-indigo", title: "Midwest Indigo", artist: "Unknown Artist", src: "/music/04%20-%20Midwest%20Indigo.mp3" },
  { id: "unknown-artist-routines-in-the-night", title: "Routines in the Night", artist: "Unknown Artist", src: "/music/05%20-%20Routines%20in%20the%20Night.mp3" },
  { id: "unknown-artist-vignette", title: "Vignette", artist: "Unknown Artist", src: "/music/06%20-%20Vignette.mp3" },
  { id: "unknown-artist-the-craving-jenna-s-version", title: "The Craving (Jenna's Version)", artist: "Unknown Artist", src: "/music/07%20-%20The%20Craving%20(Jenna's%20Version).mp3" },
  { id: "unknown-artist-lavish", title: "Lavish", artist: "Unknown Artist", src: "/music/08%20-%20Lavish.mp3" },
  { id: "unknown-artist-navigating", title: "Navigating", artist: "Unknown Artist", src: "/music/09%20-%20Navigating.mp3" },
  { id: "unknown-artist-snap-back", title: "Snap Back", artist: "Unknown Artist", src: "/music/10%20-%20Snap%20Back.mp3" },
  { id: "unknown-artist-oldies-station", title: "Oldies Station", artist: "Unknown Artist", src: "/music/11%20-%20Oldies%20Station.mp3" },
  { id: "unknown-artist-at-the-risk-of-feeling-dumb", title: "At the Risk of Feeling Dumb", artist: "Unknown Artist", src: "/music/12%20-%20At%20the%20Risk%20of%20Feeling%20Dumb.mp3" },
  { id: "unknown-artist-paladin-strait", title: "Paladin Strait", artist: "Unknown Artist", src: "/music/13%20-%20Paladin%20Strait.mp3" },
];
