// AUTO-GENERATED by scripts/gen-tracks.mjs — do not edit by hand.
// Add/remove songs by dropping files in client/public/music/ (a folder there is
// a playlist), then this file is rewritten on the next `npm run dev` /
// `npm run build` (or `npm run tracks`).
import type { Playlist, Track } from "./tracks";

export const GENERATED_TRACKS: Track[] = [
  { id: "twenty-one-pilots-midwest-indigo", title: "Midwest Indigo", artist: "Twenty One Pilots", src: "/music/04%20-%20Midwest%20Indigo.mp3", art: "/music/covers/twenty-one-pilots-midwest-indigo.jpg", playlist: "Singles", album: "Clancy", year: 2024, trackNo: 4, duration: 196 },
  { id: "twenty-one-pilots-routines-in-the-night", title: "Routines in the Night", artist: "Twenty One Pilots", src: "/music/05%20-%20Routines%20in%20the%20Night.mp3", art: "/music/covers/twenty-one-pilots-routines-in-the-night.jpg", playlist: "Singles", album: "Clancy", year: 2024, trackNo: 5, duration: 203 },
  { id: "twenty-one-pilots-vignette", title: "Vignette", artist: "Twenty One Pilots", src: "/music/06%20-%20Vignette.mp3", art: "/music/covers/twenty-one-pilots-vignette.jpg", playlist: "Singles", album: "Clancy", year: 2024, trackNo: 6, duration: 202 },
  { id: "twenty-one-pilots-the-craving-jenna-s-version", title: "The Craving (Jenna's Version)", artist: "Twenty One Pilots", src: "/music/07%20-%20The%20Craving%20(Jenna's%20Version).mp3", art: "/music/covers/twenty-one-pilots-the-craving-jenna-s-version.jpg", playlist: "Singles", album: "Clancy", year: 2024, trackNo: 7, duration: 174 },
  { id: "twenty-one-pilots-lavish", title: "Lavish", artist: "Twenty One Pilots", src: "/music/08%20-%20Lavish.mp3", art: "/music/covers/twenty-one-pilots-lavish.jpg", playlist: "Singles", album: "Clancy", year: 2024, trackNo: 8, duration: 159 },
  { id: "twenty-one-pilots-navigating", title: "Navigating", artist: "Twenty One Pilots", src: "/music/09%20-%20Navigating.mp3", art: "/music/covers/twenty-one-pilots-navigating.jpg", playlist: "Singles", album: "Clancy", year: 2024, trackNo: 9, duration: 223 },
  { id: "twenty-one-pilots-snap-back", title: "Snap Back", artist: "Twenty One Pilots", src: "/music/10%20-%20Snap%20Back.mp3", art: "/music/covers/twenty-one-pilots-snap-back.jpg", playlist: "Singles", album: "Clancy", year: 2024, trackNo: 10, duration: 210 },
  { id: "twenty-one-pilots-oldies-station", title: "Oldies Station", artist: "Twenty One Pilots", src: "/music/11%20-%20Oldies%20Station.mp3", art: "/music/covers/twenty-one-pilots-oldies-station.jpg", playlist: "Singles", album: "Clancy", year: 2024, trackNo: 11, duration: 228 },
  { id: "twenty-one-pilots-at-the-risk-of-feeling-dumb", title: "At the Risk of Feeling Dumb", artist: "Twenty One Pilots", src: "/music/12%20-%20At%20the%20Risk%20of%20Feeling%20Dumb.mp3", art: "/music/covers/twenty-one-pilots-at-the-risk-of-feeling-dumb.jpg", playlist: "Singles", album: "Clancy", year: 2024, trackNo: 12, duration: 204 },
  { id: "twenty-one-pilots-paladin-strait", title: "Paladin Strait", artist: "Twenty One Pilots", src: "/music/13%20-%20Paladin%20Strait.mp3", art: "/music/covers/twenty-one-pilots-paladin-strait.jpg", playlist: "Singles", album: "Clancy", year: 2024, trackNo: 13, duration: 389 },
  { id: "foals-a-knife-in-the-ocean", title: "A Knife in the Ocean", artist: "Foals", src: "/music/A%20Knife%20in%20the%20Ocean.mp3", art: "/music/covers/foals-a-knife-in-the-ocean.jpg", playlist: "Singles", album: "A Knife in the Ocean", duration: 413 },
  { id: "death-cab-for-cutie-a-lack-of-color", title: "A Lack of Color", artist: "Death Cab for Cutie", src: "/music/A%20Lack%20of%20Color.mp3", art: "/music/covers/death-cab-for-cutie-a-lack-of-color.jpg", playlist: "Singles", album: "A Lack of Color" },
  { id: "autoheart-agoraphobia", title: "Agoraphobia", artist: "Autoheart", src: "/music/Agoraphobia.mp3", art: "/music/covers/autoheart-agoraphobia.jpg", playlist: "Singles", album: "Agoraphobia", duration: 262 },
  { id: "foals-albatross", title: "Albatross", artist: "Foals", src: "/music/Albatross.mp3", art: "/music/covers/foals-albatross.jpg", playlist: "Singles", album: "Albatross", duration: 324 },
  { id: "death-cab-for-cutie-brothers-on-a-hotel-bed", title: "Brothers on a Hotel Bed", artist: "Death Cab for Cutie", src: "/music/Brothers%20on%20a%20Hotel%20Bed.mp3", art: "/music/covers/death-cab-for-cutie-brothers-on-a-hotel-bed.jpg", playlist: "Singles", album: "Brothers on a Hotel Bed", duration: 272 },
  { id: "bnyx-everywhere-i-go-remind-me-feat-kid-cudi", title: "EVERYWHERE I GO (REMIND ME) feat. Kid Cudi", artist: "BNYX®", src: "/music/EVERYWHERE%20I%20GO%20(REMIND%20ME)%20feat.%20Kid%20Cudi.mp3", art: "/music/covers/bnyx-everywhere-i-go-remind-me-feat-kid-cudi.jpg", playlist: "Singles", album: "EVERYWHERE I GO (REMIND ME) feat. Kid Cudi", duration: 217 },
  { id: "the-strokes-falling-out-of-love", title: "Falling out of Love", artist: "The Strokes", src: "/music/Falling%20out%20of%20Love.mp3", art: "/music/covers/the-strokes-falling-out-of-love.jpg", playlist: "Singles", album: "Falling out of Love", duration: 381 },
  { id: "pinkpantheress-girl-like-me", title: "Girl Like Me", artist: "PinkPantheress", src: "/music/Girl%20Like%20Me.mp3", art: "/music/covers/pinkpantheress-girl-like-me.jpg", playlist: "Singles", album: "Girl Like Me", duration: 146 },
  { id: "the-national-graceless", title: "Graceless", artist: "The National", src: "/music/Graceless.mp3", art: "/music/covers/the-national-graceless.jpg", playlist: "Singles", album: "Graceless", duration: 275 },
  { id: "florence-road-hanging-out-to-dry", title: "Hanging Out To Dry", artist: "Florence Road", src: "/music/Hanging%20Out%20To%20Dry.mp3", art: "/music/covers/florence-road-hanging-out-to-dry.jpg", playlist: "Singles", album: "Hanging Out To Dry", duration: 213 },
  { id: "florence-road-heavy", title: "Heavy", artist: "Florence Road", src: "/music/Heavy.mp3", art: "/music/covers/florence-road-heavy.jpg", playlist: "Singles", album: "Heavy", duration: 200 },
  { id: "foals-late-night", title: "Late Night", artist: "Foals", src: "/music/Late%20Night.mp3", art: "/music/covers/foals-late-night.jpg", playlist: "Singles", album: "Late Night", duration: 505 },
  { id: "death-cab-for-cutie-marching-bands-of-manhattan", title: "Marching Bands of Manhattan", artist: "Death Cab for Cutie", src: "/music/Marching%20Bands%20of%20Manhattan.mp3", art: "/music/covers/death-cab-for-cutie-marching-bands-of-manhattan.jpg", playlist: "Singles", album: "Marching Bands of Manhattan", duration: 269 },
  { id: "young-the-giant-mind-over-matter", title: "Mind Over Matter", artist: "Young the Giant", src: "/music/Mind%20Over%20Matter.mp3", art: "/music/covers/young-the-giant-mind-over-matter.jpg", playlist: "Singles", album: "Mind Over Matter", duration: 245 },
  { id: "the-war-on-drugs-red-eyes", title: "Red Eyes", artist: "The War On Drugs", src: "/music/Red%20Eyes.mp3", art: "/music/covers/the-war-on-drugs-red-eyes.jpg", playlist: "Singles", album: "Red Eyes", duration: 299 },
  { id: "parcels-safeandsound", title: "Safeandsound", artist: "Parcels", src: "/music/Safeandsound.mp3", art: "/music/covers/parcels-safeandsound.jpg", playlist: "Singles", album: "Safeandsound", duration: 276 },
  { id: "faye-webster-she-won-t-go-away", title: "She Won't Go Away", artist: "Faye Webster", src: "/music/She%20Won't%20Go%20Away.mp3", art: "/music/covers/faye-webster-she-won-t-go-away.jpg", playlist: "Singles", album: "She Won't Go Away", duration: 162 },
  { id: "the-postal-service-sleeping-in-remastered", title: "Sleeping In - Remastered", artist: "The Postal Service", src: "/music/Sleeping%20In%20-%20Remastered.mp3", art: "/music/covers/the-postal-service-sleeping-in-remastered.jpg", playlist: "Singles", album: "Sleeping In - Remastered", duration: 261 },
  { id: "the-national-this-is-the-last-time", title: "This is the Last Time", artist: "The National", src: "/music/This%20is%20the%20Last%20Time.mp3", art: "/music/covers/the-national-this-is-the-last-time.jpg", playlist: "Singles", album: "This is the Last Time", duration: 283 },
  { id: "death-cab-for-cutie-what-sarah-said", title: "What Sarah Said", artist: "Death Cab for Cutie", src: "/music/What%20Sarah%20Said.mp3", art: "/music/covers/death-cab-for-cutie-what-sarah-said.jpg", playlist: "Singles", album: "What Sarah Said", duration: 381 },
];

// Display order: numbered folders first, then alphabetical, then Singles.
export const GENERATED_PLAYLISTS: Playlist[] = [
  { name: "Singles", count: 30 },
];
